### PR TITLE
Add SpatRaster and stars as inputs to predict()

### PR DESCRIPTION
**Pull request by btupper**
Hi,

This pull requests primarily adds the ability to predict onto spatial raster objects `terra::SpatRaster` and `stars::stars objects`.  It does so by quietly transforming each to data frames, managing missing data records, and then assigning predicted values into the proper spatial cells.  

I made two examples in the Bigelow fork wiki (which I think don't come with the pull request).

+ [terra example](https://github.com/BigelowLab/maxnet/wiki/terra)

+ [stars example](https://github.com/BigelowLab/maxnet/wiki/stars)

I also have added some minor optional arguments to the function that plots responses.

I hope these might be useful.

Ben

### CODE REVIEW

**Comment by mrmaxent** [comment]
Hey Ben,

Thanks for the work you've been doing on this.  Some thoughts on this:

I'm comfortable enough not personally testing your new code that supports terra and spatraster, and in the release notes I'll say that that functionality is a kind of beta release.  It's fairly self-contained, so it should be easy to tell if users run into issues with it.  Can you commit to addressing any problems that users might find with it?

Your main addition to the code looks like it could be substantially simplified and cleaned up.  There are quite a few code lines that are repeated for the three data types, with minor variations, where a single version would work for them all.  (e.g., a vector of NA values could be made once, and the predictions spliced into it once.)  The original number of cases is referred to as "N" in one case, and terra::ncell(S) in another.  For spatrasters, you create a placeholder full of NA values, then replace it later on without using it.

I like the addition of roxygen-style documentation, but don't really like having mixed documentation styles.  Would you like to convert the rest of the documentation to roxygen-style, for consistency?

For predict.maxnet, I would prefer to not have the "incompletes" argument, and instead just produce NA values for incomplete cases.  This change wouldn't be backwards-compatible, but I think that's ok because silently dropping incomplete cases feels like a bug.  If a user then really wants to drop NA values from the output they can use na.omit as easily as passing an extra argument to predict.maxent.  But I think there is an easier way to produce NA's where necessary -- did you try adjusting the na.action option?  Using na.pass instead of the default na.omit might do what we need.

https://stackoverflow.com/questions/6447708/model-matrix-generates-fewer-rows-than-original-data-frame

**Comment by btupper** [comment]
Hi,

Yes, I can commit to addressing problems.

Yes, I can work on simplifying/streamlining.

Yes, I can tranlate the code to roxygen style.

Yes, I can change the NA handling to preserve NAs.

A timetable (other than adressing problems) is much harder to commit to, but happily my employer wants to use maxnet so it shouldn't be too far back on the stove.

Best wishes,
Ben

**Comment by btupper** [comment]
Hi,

I think this resolves the following...

+ roxygen documentation only

+ NAs passed in `predict()`

+ streamlined handling for `SpatRaster` and `stars` in `predict()`

The latter was easy to resolve once NAs were passed through.  Still there are syntactic difference between `terra` and `stars` that can't be avoided. 

The examples in the fork's wiki appear to work with the update without issue.

[stars](https://github.com/BigelowLab/maxnet/wiki/stars)

[terra](https://github.com/BigelowLab/maxnet/wiki/terra) 


Best wishes,
Ben

**Comment by mrmaxent** [comment]
Hi Ben,

Thanks for this, it looks pretty good.  Just a couple of things stand out:
- where you have importFrom(stats, ...), I think there are some things we no longer use (like complete.cases).

For the changes to predict.maxnet, I think it can still get a little cleaner.  What do you think of this version?  It is a few lines shorter, and the processing for each new raster data format is contained in a single "if" at the top and a single "if" at the end.  I wasn't sure where to make suggested edits, so I'll just paste it here:

predict.maxnet <-
  function(object, newdata, clamp=T, type=c("link","exponential","cloglog","logistic"), ...)
  {
    
    na_action <- options("na.action")[[1]]
    on.exit(options(na.action = na_action))
    options(na.action = "na.pass")
    
    newdataframe <- newdata
    if (is_stars <- inherits(newdata, "stars")) {
      if (!requireNamespace("stars", quietly = TRUE)) {
        stop("package stars required, please install it first")
      }
      newdataframe <- as.data.frame(newdata)[, -c(1,2)]
    }
    if (is_spatraster <- inherits(newdata, "SpatRaster")) {
      if (!requireNamespace("terra", quietly = TRUE)) {
        stop("package terra required, please install it first")
      }
      newdataframe <- as.data.frame(newdata, na.rm = FALSE)
    }
    
    
    if (clamp) {
      for (v in intersect(names(object$varmax), names(newdataframe))) {
        newdataframe[,v] <- pmin(pmax(newdataframe[,v], object$varmin[v]), object$varmax[v])
      }
    }
    terms <- sub("hinge\\((.*)\\):(.*):(.*)$", "hingeval(\\1,\\2,\\3)", names(object$betas))
    terms <- sub("categorical\\((.*)\\):(.*)$", "categoricalval(\\1,\"\\2\")", terms)
    terms <- sub("thresholds\\((.*)\\):(.*)$", "thresholdval(\\1,\\2)", terms)
    f <- formula(paste("~", paste(terms, collapse=" + "), "-1"))
    mm <- model.matrix(f, data.frame(newdataframe))
    if (clamp) mm <- t(pmin(pmax(t(mm), object$featuremins[names(object$betas)]), 
                            object$featuremaxs[names(object$betas)]))
    link <- (mm %*% object$betas) + object$alpha
    type <- match.arg(type)
    r <- switch(tolower(type[1]),
                "exponential" = exp(link),
                "cloglog" = 1-exp(0-exp(object$entropy+link)),
                "logistic"= 1/(1+exp(-object$entropy-link)),
                link)
    
    if (is_stars){
      S <- newdata[1]
      S$pred <- r
      names(S) <- "pred"
      return(S)
    } 
    if (is_spatraster)
      S <- newdata[[1]]
      terra::values(S) <- r
      names(S) <- "pred"
      return(S)
      }
    } 
    
    return(r)
  }

**Comment by btupper** [comment]
Hi,

I suffer from a highly developed short-term memory thus I tend to spread code out to make it easier for me to decode later, but I certainly understand your desire to tighten things up.  I think the most important thing is that it works the way you want it to work.

I think the latest commit resolves the extraneous import of `stats::complete.cases` (all the others seem to be in use elsewhere in the package).  These are declared in `R/maxnet-package.R` which roxygen uses to build the `NAMESPACE` file.

This latest commit successfully completes the two examples (terra and stars) in the forked repository's wiki.  

The use of `terra` and `stars` here is pretty light and shallow - I think providing the capability to deal with these data types going forward should be easy.

Thanks for considering these additions.  Are there other things to tweak?

Cheers,
Ben

**Comment by mrmaxent** [comment]
OK, now merged.  Thanks for the new stuff, Ben.

**Pull request merged**
